### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by Mrkkew** [liu-xb/GCMT#1]
When would you release your source code?

**Comment by Liuzhengfa88** [comment]
When would you release your source code?

**Comment by liu-xb** [comment]
I'm currently working on my thesis. Source code will be collected and released right after I've defended my thesis, which is about September 25 or earlier. Sorry for delaying.

**Comment by liu-xb** [comment]
I have released the code of Graph Consistency Constraint in gcc.zip.

**Comment by krmui** [comment]
The code in the compressed package you provided is incomplete. Can you supplement it，thanks

**Comment by liu-xb** [comment]
I apologize for the delay! I have upload codes, models, and training logs. Thanks for your attention!
